config/routes.rb
Rails.application.routes.draw do
  # these routes are for showing users a login form, logging them in, and logging them out.
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'


  resources :costs

  root 'costs#index'

  namespace :api do
    resources :costs, :sessions, :weekstats, :monthstats, :budgets, :state_reports
  end


end

app/models/cost.rb
class Cost < ApplicationRecord
  belongs_to :user
  validates :price, presence: true
  validates :price,:numericality => { :greater_than_or_equal_to => 0 }
end

app/controllers/api/costs_controller.rb
module Api
  class CostsController < Api::BaseController
    def index
      @costs = Cost.all
      puts "costs.count = #{@costs.count}"
      render :json => @costs.to_json
    end


    def create
      @cost = Cost.new(cost_params)
      @cost.user_id = @current_user.id
      if @cost.save
        render :json => @cost.to_json
      else
        render nothing: true, status: :bad_request
      end
    end


      def destroy
        @cost = Cost.find(params[:id])
        @cost.destroy
        render :json => {:message => "Success"}, status: :ok
      end


    private
    def cost_params
      params.require(:cost).permit(:price, :store, :comment)
    end
  end
end

app/controllers/costs_controller.rb
class CostsController < ApplicationController
  before_filter :authorize

  def index
    @costs = Cost.all
    respond_to do |format|
      format.html
      format.json { render :json => @costs.to_json }
    end
  end

  def show
    @cost = Cost.find(params[:id])
  end

  def new
    @cost = Cost.new
  end

  def edit
    @cost = Cost.find(params[:id])
  end

  def create
    @cost = Cost.new(cost_params)
    @cost.user_id = session[:user_id]
    if @cost.save
      redirect_to @cost
    else
      render 'new'
    end
  end

  def update
    @cost = Cost.find(params[:id])

    if @cost.update(cost_params)
      redirect_to @cost
    else
      render 'edit'
    end
  end

  def destroy
    @cost = Cost.find(params[:id])
    @cost.destroy

    redirect_to costs_path
  end

  private
  def cost_params
    params.require(:cost).permit(:price, :store, :comment)
  end
end

app/helpers/costs_helper.rb
module CostsHelper
end

app/views/costs/_form.html.erb
<%= form_for @cost do |f| %>

  <% if @cost.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@cost.errors.count, "error") %> prohibited
        this cost from being saved:
      </h2>
      <ul>
        <% @cost.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :price %><br>
    <%= f.number_field :price, :class => 'text_field', :step => 0.01 %>
  </p>
  <p>
    <%= f.label :store %><br>
    <%= f.select :store, Market.categories.collect { |c| [ c, c ] }%>
  </p>

  <p>
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/costs/edit.html.erb
<h1>Editing cost</h1>

  <%= render 'form' %>

<%= link_to 'Back', costs_path %>

app/views/costs/index.html.erb
<h1>Listing costs</h1>
<%= link_to 'New cost', new_cost_path %>
<table>
  <tr>
    <th>Creation Timestamp</th>
    <th>Price</th>
    <th>Store</th>
    <th>Comment</th>
    <th>By</th>
  </tr>

  <% @costs.each do |cost| %>
    <tr>
      <td><%= cost.created_at %></td>
      <td><%= cost.price %></td>
      <td><%= cost.store %></td>
      <td><%= cost.comment %></td>
      <td><%= cost.user.name %></td>
    </tr>
  <% end %>
</table>

app/views/costs/new.html.erb
<h1>New Cost</h1>

  <%= render 'form' %>

  <%= link_to 'Back', costs_path %>

app/views/costs/show.html.erb
<h1> That's your cost :O </h1>

<p>
  <strong>Price:</strong>
  <%= @cost.price %>
</p>

<p>
  <strong>store:</strong>
  <%= @cost.store %>
</p>


<p>
  <strong>Comment:</strong>
  <%= @cost.comment %>
</p>


<p>
  <strong>Time:</strong>
  <%= @cost.created_at %>
</p>


<%= link_to 'Back', costs_path %>
<%= link_to 'Edit', edit_cost_path(@cost) %>